server:
  port : 8090

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

externalApi:
  tvmaze:
    url: https://api.tvmaze.com
  lastfm:
    url: http://ws.audioscrobbler.com/2.0